blueprint:
  name: Hue Tap Dial Switch - Vollständige Steuerung
  description: Weisen Sie Aktionen allen Tasten des Hue Tap Dial Switch zu.
  domain: automation
  input:
    hue_tap_switch:
      name: Hue Tap Dial Switch
      selector:
        entity:
          domain: sensor
          integration: hue

trigger:
  - platform: state
    entity_id: !input 'hue_tap_switch'
    to: '1_click'
  - platform: state
    entity_id: !input 'hue_tap_switch'
    to: '1_hold'
  - platform: state
    entity_id: !input 'hue_tap_switch'
    to: '1_rotate_right'
  - platform: state
    entity_id: !input 'hue_tap_switch'
    to: '1_rotate_left'
  # Fügen Sie hier die weiteren Zustände für die anderen Tasten hinzu

action:
  - choose:
      - conditions:
          - "{{ trigger.to_state.state == '1_click' }}"
        sequence:
          # Aktionen für Taste 1 - einfaches Drücken
      - conditions:
          - "{{ trigger.to_state.state == '1_hold' }}"
        sequence:
          # Aktionen für Taste 1 - gedrückt halten
      - conditions:
          - "{{ trigger.to_state.state == '1_rotate_right' }}"
        sequence:
          # Aktionen für Taste 1 - Drehen nach rechts
      - conditions:
          - "{{ trigger.to_state.state == '1_rotate_left' }}"
        sequence:
          # Aktionen für Taste 1 - Drehen nach links
      # Fügen Sie hier die `choose` Sequenzen für die anderen Tasten hinzu

# Beispiel für Taste 2
  - choose:
      - conditions:
          - "{{ trigger.to_state.state == '2_click' }}"
        sequence:
          # Aktionen für Taste 2 - einfaches Drücken
      - conditions:
          - "{{ trigger.to_state.state == '2_hold' }}"
        sequence:
          # Aktionen für Taste 2 - gedrückt halten
      - conditions:
          - "{{ trigger.to_state.state == '2_rotate_right' }}"
        sequence:
          # Aktionen für Taste 2 - Drehen nach rechts
      - conditions:
          - "{{ trigger.to_state.state == '2_rotate_left' }}"
        sequence:
          # Aktionen für Taste 2 - Drehen nach links
# Wiederholen Sie diesen Abschnitt für Taste 3 und 4 mit den entsprechenden Zuständen

# Beispiel für Taste 3
  - choose:
      - conditions:
          - "{{ trigger.to_state.state == '3_click' }}"
        sequence:
          # Aktionen für Taste 3 - einfaches Drücken
      - conditions:
          - "{{ trigger.to_state.state == '3_hold' }}"
        sequence:
          # Aktionen für Taste 3 - gedrückt halten
      - conditions:
          - "{{ trigger.to_state.state == '3_rotate_right' }}"
        sequence:
          # Aktionen für Taste 3 - Drehen nach rechts
      - conditions:
          - "{{ trigger.to_state.state == '3_rotate_left' }}"
        sequence:
          # Aktionen für Taste 3 - Drehen nach links
		  
# Beispiel für Taste 4
  - choose:
      - conditions:
          - "{{ trigger.to_state.state == '4_click' }}"
        sequence:
          # Aktionen für Taste 4 - einfaches Drücken
      - conditions:
          - "{{ trigger.to_state.state == '4_hold' }}"
        sequence:
          # Aktionen für Taste 4 - gedrückt halten
      - conditions:
          - "{{ trigger.to_state.state == '4_rotate_right' }}"
        sequence:
          # Aktionen für Taste 4 - Drehen nach rechts
      - conditions:
          - "{{ trigger.to_state.state == '4_rotate_left' }}"
        sequence:
          # Aktionen für Taste 4 - Drehen nach links